### ISSUE TITLE
GoGo Protobuf is deprecated/unmaintained 

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#1063]
https://github.com/gogo/protobuf is deprecated and doesn't support Google's Protobuf APIv2. We should probably look for a replacement.

Possible alternatives:

* https://github.com/planetscale/vtprotobuf
* https://github.com/CrowdStrike/csproto

**Comment by orpheuslummis** [comment]
any special reason why to prefer https://github.com/planetscale/vtprotobuf over classic https://github.com/protocolbuffers/protobuf-go *outside* of "being optimized" ?

**Comment by orpheuslummis** [comment]
https://github.com/cosmos/gogoproto looking promising to keep the current approach
