### ISSUE TITLE
Allow string/named substitution of field indexes

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1169]
Part of #1002

I.e. instead of:
```
/Users/Schema/Fields/1
```
Users should be able to specify:
```
/Users/Schema/Fields/Age
```
Try and bear in mind whilst implementing that we'll likely want similar for collection name, kind and CrdtType.

Use of indexes should still be allowed else we'll break from the JSON patch spec - this should just be syntax sugar on top. Unless ofc we change the data model to map based, which could create a whole bunch of other issues (ordering, collisions, internal inefficiencies, etc) - I really do not want to go down that route, especially right now.

**Comment by islamaliev** [comment]
bug bash result:
ran locally a defradb node and ran commands similar to ones from integration tests.
No issues found
