### ISSUE TITLE
No tests for the validation of the GraphQL endpoint's schema

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1206]
The GraphQL endpoint exposes a schema through introspection. There should be tests to validate the schema, e.g. matching validation that GraphQL clients use.

**Comment by AndrewSisley** [comment]
@orpheuslummis can this be closed?

**Comment by orpheuslummis** [comment]
Yes I'll close it when I get back to my computer in 1-2h

**Comment by orpheuslummis** [comment]
Unless you can do it now :)
