### ISSUE TITLE
Remove date/copyright from CLI printed information

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#1229]
See: https://github.com/sourcenetwork/defradb/blob/0cddca5685a05dda0a2bbcc772a99cf7cd7106ea/cli/root.go#L31

**Comment by shahzadlone** [comment]
Ops I saw this unassigned and in the todo so assigned and was gunna do it, but see there is a PR for this already. Should this be in review then or in progress instead of todo for v0.6 @fredcarle

**Comment by fredcarle** [comment]
> Ops I saw this unassigned and in the todo so assigned and was gunna do it, but see there is a PR for this already. Should this be in review then or in progress instead of todo for v0.6 @fredcarle

Yes we can move that to in review. I was gonna pick that PR up tomorrow to clean it up and merge it. If you want to do it though be my guess. I already had approved it with a couple suggestions.
