### ISSUE TITLE
`TestP2PWithSingleDocumentSingleUpdateDoesNotSyncFromUnmappedNode` occasionally fails

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1252]
Obtained on develop https://github.com/sourcenetwork/defradb/commit/f7673947122e05545026a8a0a8dcbc760134c849

Full log https://gist.github.com/orpheuslummis/481ae67e4e05ab827b11ac3caf177bf3

**Comment by AndrewSisley** [comment]
Not seen this in a while, is probably fixed
