### ISSUE TITLE
Make `dockey` and `id` request arguments more consistent

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#1272]
Sometimes we use `dockey` and sometimes we use `id` as arguments to request queries/mutations.

See also https://github.com/sourcenetwork/defradb/issues/1467 - it might be worth doing these together.

**Comment by AndrewSisley** [comment]
Discussed in discord here: https://discord.com/channels/427944769851752448/1109107500499881994

These should all be named to `_key` and `_keys`

**Comment by shahzadlone** [comment]
> Discussed in discord here: [discord.com/channels/427944769851752448/1109107500499881994](https://discord.com/channels/427944769851752448/1109107500499881994)
> 
> These should all be named to `_key` and `_keys`

Did you mean `key` and `keys`? I thought we don't want to do the underscores on non-commit/`_version` fields or input parameters to operations.

**Comment by AndrewSisley** [comment]
I think that comment might have predated the most recent chat
