### ISSUE TITLE
Allow using `object` as an alias for `object_id` in relationships 

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#1279]
Sub-Tasks:
- [x] GroupBy
- [ ] Create
- [ ] Update

Given a schema such as
```graphql
type Book {
    name: String
    rating: Float
    author: Author
}
```
we currently need to use `author_id` in some cases to represent the `author`. For example,
```graphql
query {
  Book(groupBy: [author_id]) {
    author {
      name
    }
    _group {
      name
    }
  }
}
```
or 
```graphql
mutation {
  create_Book(data: "{\"name\": \"Some book\", \"rating\": 8.3, \"author_id\": \"some_author_dockey\"}") {
    _key
  }
}
```

Given the schema and what will be intuitive to users, it would make sense to allow 
```graphql
query {
  Book(groupBy: [author]) {
    author {
      name
    }
    _group {
      name
    }
  }
}
```
and
```graphql
mutation {
  create_Book(data: "{\"name\": \"Some book\", \"rating\": 8.3, \"author\": \"some_author_dockey\"}") {
    _key
  }
}
```

**Comment by AndrewSisley** [comment]
Independent feedback from a partner (Digital Gaia) on this issue:

> The standard of naming the field that refers to the external type as type_id  is a really unintuitive. 
>
> E.g. 
type Basket {
  items: [Food]
}
> 
> type Food {
  basket: Basket
}
> 
> 
> When specifying which basket your food belongs to you use:
food = {
  "basket_id": basket_key
}
> 
> 
> Is there any technical reason that it couldn't just be:
food = {
  "basket": basket_key
}
> 
> 
> The error:
The given field does not exist. Name: basket
> 
> 
> Is a common error, but it's annoying to debug because you check your schema and you're like, "It's right f***ing there!"

**Comment by AndrewSisley** [comment]
This ticket is loosely related to https://github.com/sourcenetwork/SIPs/discussions/10

**Comment by fredcarle** [comment]
Possibly related to #681

**Comment by jsimnz** [comment]
Not related 😅

**Comment by shahzadlone** [comment]
Should solve with: https://github.com/sourcenetwork/defradb/issues/1551

**Comment by fredcarle** [comment]
I think that would make sense yes.

**Comment by fredcarle** [comment]
> > So then would we also want the following to return the author_id if we do:
> 
> I think that breaks the GQL spec (author is an object, not a scalar, and there are no child members defined), and might confuse people anyway as they may expect it to return the full author object. As well as being a bit unpleasent in the way that the return type changes shape depending on the declaration of child properies.

Oh yes I remember from a previous conversation that we said that if users wanted the object_id they should do it like this:
```graphql
query {
  Book {
    name
    author{
      _docID
      name
    }
  }
}
```

**Comment by shahzadlone** [comment]
> I think that would make sense yes.

I am not sure if that is good though. As Andy mentioned I think that breaks the spec, inconsistent shape and also means that we can use alias only when there is not a sub-selection of `author` (as using it if there is might give duplicate field selection) this we could avoid by adding an underscore before the alias, but I think is overall going to confuse people more.

Maybe we limit the cases where we support alias (one use case is the `groupBy` one).

**Comment by fredcarle** [comment]
Yes I agreed with Andy as you can see above. For some reason I had forgotten about the spec and the previous conversation we had on the subject.

**Comment by shahzadlone** [comment]
Ok proceeding further then for completeness, we want to have this:
```
query {
	Book(groupBy: [author]) {
		author_id
		_group {
			name
			rating
			author {
				name
				age
			}
		}
	}
}
```

Instead of this:
```
query {
	Book(groupBy: [author]) {
		author
		_group {
			name
			rating
			author {
				name
				age
			}
		}
	}
}
```

Note: Use of alias in `groupBy`, not while selecting selecting fields.

**Comment by jsimnz** [comment]
> Oh yes I remember from a previous conversation that we said that if users wanted the object_id they should do it like this:

This was in the context of more long term plans, but if it makes things easier now, we can certainly explore it.

> Ok proceeding further then for completeness, we want to have this:

The first query here wouldn't be quite right, you don't want the `author` field inside the `_group` selection, if that is the field you are grouping By.

It would be:
```graphql
query {
	Book(groupBy: [author]) {
		author_id  // Or in future _authorID
               // or
               author {
			name
			age
		}
		_group {
			name
			rating
			
		}
	}
}
```

**Comment by jsimnz** [comment]
But I do think in general, given this convo, its prob best to slowly deprecate the `author_id` external field

**Comment by AndrewSisley** [comment]
I think `Book(groupBy: [author]) {` would block us from allowing grouping by child items. A similar typing issue exists for other input params, including `filter` where we definitely do support the targeting of child params (e.g. `Author(filter: {published: {rating: {_gt: 4.8}}}) {`.

**Comment by shahzadlone** [comment]
> The queries here wouldn't be quite right, you don't want the `author` field inside the `_group` selection, if that is the field you are grouping By.

Queries might be none-sensible as generally the content is already grouped by the field as you mentioned, but it is a valid query and we have tests that assert a similar query (could be some odd requirement where the user wants to have this structure). Just shared that query for a more exhaustive visualization.

**Comment by shahzadlone** [comment]
As `groupBy` alias is merged, I was thinking about the `filter` alias.

Currently, we can do:

```gql
query {
	Book(filter: {author: {_key: {_eq: "bae-41598f0c-19bc-5da6-813b-e80f14a10df3"}}}) {
		name
	}
}
```

OR

```gql
query {
	Book(filter: {author_id: {_eq: "bae-41598f0c-19bc-5da6-813b-e80f14a10df3"}}) {
		name
	}
}
```

With Alias we would then introducing a 3rd way to do the same thing:
```gql
query {
	Book(filter: {author: "bae-41598f0c-19bc-5da6-813b-e80f14a10df3"}) {
		name
	}
}
```

Moreover, Note that the following is valid:
```gql
query {
	Book(
		filter: {
			author: {_key: {_eq: "bae-41598f0c-19bc-5da6-813b-e80f14a10df3"}},
			author_id: {_eq: "bae-41598f0c-19bc-5da6-813b-e80f14a10df3"}
		}
	) {
	name
	}
}
```

Question: Are we sure we want to introduce a 3rd way new way to do the same filter? This also means it will conflict with a second filter if it is a related filter, as alias and related field selection will clash names like the following:
```gql
query {
	Book(
		filter: {
			author: {name: {_eq: "Jim"}},
			author: "bae-41598f0c-19bc-5da6-813b-e80f14a10df3"
		}
	) {
	name
	}
}
```

Would be in favor to not alias related object id field on `filter` as it's unnecessary edge cases to handle and introducing more ways to do the same thing just for the sake of syntactic sugar.
