### ISSUE TITLE
Migrate ipfs dependencies to ipfs' boxo

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1288]
Many Go modules under github.com/ipfs have moved to boxo. It is what resulted from the effort to consolidate the repositories of the IPFS project https://github.com/ipfs/kubo/issues/8543 (AFAIK)

https://github.com/ipfs/boxo#migrating-to-boxo

**Comment by fredcarle** [comment]
v0.8.0 has been release. Unblocked
