### ISSUE TITLE
Use Go toolchain install instructions in README

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1323]
`go install https://github.com/sourcenetwork/defradb@latest` or more specifically with our current file structure `go install github.com/sourcenetwork/defradb/cmd/defradb@latest`

```
o@blitz ~ % go install github.com/sourcenetwork/defradb/cmd/defradb@latest
go: github.com/sourcenetwork/defradb/cmd/defradb@latest (in github.com/sourcenetwork/defradb@v0.4.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by jsimnz** [comment]
@fredcarle I cant get the ellipsis approach to work, are you sure thats correct? I know you could do it before the go mod changes, but I dont think you can do go install without specifying a version.

Can you post the exact command your running?

**Comment by fredcarle** [comment]
No more replace in mod file.
