### ISSUE TITLE
Test utils tries to read from WaitForPushLogByPeerEvent with 2 IDs

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1368]
E.g.
```
for i := 0; i < targetToSourceEvents[waitIndex]; i++ {
    err := sourceNode.WaitForPushLogByPeerEvent(targetNode.PeerID())
    require.NoError(t, err)
}
for i := 0; i < sourceToTargetEvents[waitIndex]; i++ {
    err := targetNode.WaitForPushLogByPeerEvent(sourceNode.PeerID())
    require.NoError(t, err)
}
```

This wont work properly, as the first call to `WaitForPushLogByPeerEvent` may consume and discard chan items for the second peer id.

May be responsible for some of the test flakiness, particularly where bi-directional syncs are expected.

**Comment by AndrewSisley** [comment]
I am at least partially incorrect here and may close this issue shortly

**Comment by fredcarle** [comment]
@AndrewSisley I think we can close this issue. Each wait is specific to a node so the first one won't discard anything on the second one.

**Comment by AndrewSisley** [comment]
Cheers Fred
