### ISSUE TITLE
Errors dont Marshal nicely to json

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1383]
Our errors, 3rd party errors, and std lib errors do not marshal nicely to json (typically marshal to an empty object).  This means that on request error, and empty object is sent back to GQL clients, which is not very useful to them.

e.g.:
```
{
  "errors": [
    {}
  ],
  "data": null
}
```
Issue also visible in #1382 

EDIT: Discussed over discord, agreed to handle error serialisation within the http package.

**Comment by orpheuslummis** [comment]
https://discord.com/channels/427944769851752448/1098794315234431086

**Comment by AndrewSisley** [comment]
when fixing, please also ensure that the explicit/external transaction code path is also tested/fixed

**Comment by AndrewSisley** [comment]
This is a bit odd actually, as we have a test that covers this, and is appears to be working (I tweaked the error message to fail it, and it failed). `TestMutationCreateSimpleDoesNotCreateDocGivenDuplicate`
