### ISSUE TITLE
Only first GraphQL request in a HTTP request is applied

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1395]
(not sure this title is clear, but anyway)

I suggest that either it could be giving an error or be documented behavior instead of silently only applying the first query.

e.g. with the HTTP Request sending two GraphQL requests,

```
query A {
  User {
    _key
  }
}

mutation B {
    create_User(data: "{\"name\": \"Two\", \"age\": 7}") {
      _key
    }
}
```

only `A`, the first one, is applied.

**Comment by jsimnz** [comment]
This is actually basically defined as per the spec: https://spec.graphql.org/June2018/#sec-Executing-Requests

GQL will only execute a single operation. If multiple are given, the need to be named, and you need to specify the name of the operation to run.

Theres an open issue to change this: https://github.com/graphql/graphql-spec/issues/375

**Comment by orpheuslummis** [comment]
Perhaps a future issue could be made for this, or this issue could be renamed and implemented as "Support GraphQL batching" once a GraphQL spec has it.
