### ISSUE TITLE
API endpoint and CLI command to expose schemaID straightforwardly

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1407]
As a user, I want to be able to create a schema then obtain its ID easily. This is needed for setting up a pubsub network syncing specific collections, for instance.

For example, perhaps the simplest implementation is for the `schema/load` endpoint to return schemaID upon successful schema creation.

Previous related discussion by Islam about this https://github.com/sourcenetwork/defradb/discussions/1284 https://github.com/sourcenetwork/defradb/discussions/1285

This goal can be seen as part of the bigger API story around schemas, which might be best to discuss elsewhere, but I wanted to record this specific goal of it...

**Comment by orpheuslummis** [comment]
It seems better to not expose the "p2pcollection" system in language clients until this is completed.

**Comment by nasdf** [comment]
closed by #1839
