### ISSUE TITLE
CLI integration tests are really slow

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1409]
The new CLI tests in `tests/integration/cli` take 36 seconds to run on my machine (`go test ./...`, no race flag, etc).  This is more than double the cost of the rest of the test suite put together and represents a significant cost increase to running the tests locally.

I suggest we either find a way to make them much faster, or to exclude them by default from `go test ./...` somehow.

**Comment by orpheuslummis** [comment]
There two complementary approaches: remove time buffers by exposing event system externally via API, or parallellize the tests

**Comment by orpheuslummis** [comment]
for the record, i made all the CLI integration tests parallel and this is what ensued https://gist.github.com/orpheuslummis/75b6a6e477d1d0add86161b16ac4add2

**Comment by orpheuslummis** [comment]
there are at least these data races when having concurrent Defra instances in the same process:
- in the `logging` system
- the CLI integration test suite with `captureOutput` re-using the same `stderr, stdout`, but could be potentially fixed with a mutex

**Comment by shahzadlone** [comment]
> there are at least these data races when having concurrent Defra instances (each with different rootdir and config) in the same process:
> 
> * in the `logging` system
> * the CLI integration test suite with `captureOutput` re-using the same `stderr, stdout`, but could be potentially fixed with a mutex

Could these by linked to why https://github.com/sourcenetwork/defradb/issues/1412 is happening?

**Comment by AndrewSisley** [comment]
Removal from default `make test` has been broken out to this issue: https://github.com/sourcenetwork/defradb/issues/1642

This issue will be renamed, and scoped to making the CLI tests faster (which still affect full test runs (e.g. in CI)

**Comment by AndrewSisley** [comment]
Fixed by @nasdf in https://github.com/sourcenetwork/defradb/pull/1839/files
