### ISSUE TITLE
commits input arg is call `field`, but the corresponding field is call `fieldId`

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1452]
e.g.:
```
commits (field: "1") {
	fieldId
}
```
should be:
```
commits (fieldId: "1") {
	fieldId
}
```

**Comment by orpheuslummis** [comment]
is there a consensus convention for the codebase on using `Id` vs `ID` ?

**Comment by AndrewSisley** [comment]
> is there a consensus convention for the codebase on using `Id` vs `ID` ?

I think we have spoken a few times about this, but I cant remember any agreement.  We currently have both though, and that is not nice.
