### ISSUE TITLE
GraphQL `commits` field metadata incorrect

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1457]
The `commits` field:
```
commits(
cid: ID
depth: Int
dockey: ID
field: String
groupBy: [commitFields!]
limit: Int
offset: Int
order: commitsOrderArg
): [Commit]

Returns a set of commits matching any provided criteria. If no arguments are
provided all commits in the system will be returned.
```

Issue: `depth: Int` seems required currently. If that's desired behavior, `Int` should be marked as `Int!`

Issue: If depth is required, "If no arguments are provided all commits in the system will be returned." should be updated to indicate that.

Currently,

```
query {
  commits() {
    dockey
  }
}
```

yields

```
{
  "errors": [
    "Syntax Error GraphQL request (2:10) Unexpected empty IN ()\n\n1: query {\n2:   commits() {\n            ^\n3:     dockey\n"
  ],
  "data": null
}
```

**Comment by jsimnz** [comment]
Not sure if it answers the issue, but 

```
query {
    commits() {
        ...
    }
}
```

Isn't a valid GQL query. You can't have an empty argument set if you have brackets, you must have arguments.

**Comment by orpheuslummis** [comment]
oops you're right.

with:
```
query {
  commits {
    dockey
  }
}
```

I'm obtaining:
```
{
  "errors": [
    "commit Delta missing field name"
  ],
  "data": null
}
```

**Comment by AndrewSisley** [comment]
none of the input args are required, and we have tests that assert this, e.g. `TestQueryCommits`

```
query {
  commits {
    dockey
  }
}
```
Looks like a planner bug.

**Comment by AndrewSisley** [comment]
> oops you're right. the original issue still stands but slightly differently:
> 
> with:
> 
> ```
> query {
>   commits {
>     dockey
>   }
> }
> ```
> 
> I'm obtaining:
> 
> ```
> {
>   "errors": [
>     "commit Delta missing field name"
>   ],
>   "data": null
> }
> ```

I cant actually reproduce this, seems to work fine if you modify `TestQueryCommits` to return dockey instead of cid.  What database state do you have?

**Comment by AndrewSisley** [comment]
Ahhh... I know what you've done.  You are running this against an already created database.  There was a breaking change that got merged yesterday that will break commit queries for existing databases, you are seeing that.

**Comment by orpheuslummis** [comment]
Ah, now I've run it against a fresh database instance and the issue doesn't occur. Thanks for explaining. Closing
