### ISSUE TITLE
When adding a schema include collection(s) name and ID (global)

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#1498]
At the moment, the only way to get the collection ID if you want to do something like a p2pcollection is to run
```graphql
query {
  User{
    _version {
      schemaVersionID
    }
  }
}
```

This is problematic for a number of reasons. 1) the schemaVersionID is a changing value based on future schema updates/migrations 2) It requires there to be an existing record in the collection for any response to be returned. 

There is already an issue for a richer API to get information on existing collections #1407. The first step this issue is proposing is to include the information when *adding* the schema. This includes the client API, CLI API, and HTTP API.

**Comment by orpheuslummis** [comment]
related: https://github.com/sourcenetwork/defradb/issues/1407
