### ISSUE TITLE
SequenceKey produces unexpected string

### ISSUE THREAD

**Issue by islamaliev** [sourcenetwork/defradb#1523]
**Describe the problem**
when calling:
```go
_, err = db.getSequence(ctx, txn, core.COLLECTION)
```

it will store a value with the key `"/seq//collection/names"` with an excessive "/"

**To Reproduce**
Just start DefraDB. It happens on start.

**Expected behavior**
It should store a value with the key `"/seq/collection/names"`

**Comment by AndrewSisley** [comment]
This appears to have been fixed
