### ISSUE TITLE
Simple version migration import/export

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#1544]
Export the data in a way that it can be imported without taking the DAG into account. This is to help partners update from one version of Defra to an other during development.

**Comment by AndrewSisley** [comment]
Obvious thought came quite late - we should be able to use Lens to do this, and long term I would strongly encourage us to do so

**Comment by fredcarle** [comment]
> It would be very easy to also skip the import-export step too, and just pipe from one (old) defra instance to another (new) defra instance.

The old to new instance situation might be annoying to users as they would need 2 separate `.defradb` directories and have them use different configs.

**Comment by AndrewSisley** [comment]
> The old to new instance situation might be annoying to users as they would need 2 separate `.defradb` directories and have them use different configs.

They'd need kind of need that anyway no?  I thought you were basically going export the full db (i.e. copy it), purge the db, update the db, then import. If piping can always drop the source and move the destination as a last step - should even be safer as they can then validate that the destination actually works before purge.

**Comment by fredcarle** [comment]
The simple version is: export -> delete -> create -> import. I wouldn't want to impose a change in configuration for that to work. We could however just rename the data file temporarily and if something goes wrong that can always be reverted. There would be no need to change configs.

**Comment by AndrewSisley** [comment]
> We could however just rename the data file temporarily and if something goes wrong that can always be reverted

:+1: of course, cheers.  And this is just a quick/early/semi-temporary solution right?

(also just reemphasising that Lens could/should be used with the import/export to/from file option too)

**Comment by fredcarle** [comment]
Showcasing Lens is a fair point. Lets have a chat about what that would look like sometime next week.
