### ISSUE TITLE
Licensing to have full documentation on pkg.go.dev

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#155]
As per https://pkg.go.dev/license-policy only limited package and module information will be made available if the license of a submitted package is not part of the list. Currently unsure how strongly this policy is enforced. One possible solution is dual licensing.

**Comment by jsimnz** [comment]
We won't be able to get our code hosted on `pkg.go.dev` per their licensing descision

See: https://github.com/golang/go/issues/59183#issuecomment-1535426549
