### ISSUE TITLE
Track schema version history

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1556]
Part of https://github.com/sourcenetwork/defradb/issues/1002

At the moment users need to specify the destination and source schema versions for their migrations.  This is error prone, can create divergent/overlapping migrations and is unnecessary hassle for them.

They should only need to provide the destination schema version. 

To do this we can create an index, and move the existing schema index (which stores the schema json representation), roughly as follows:
```
// this already exists, without the `/v` (CollectionSchemaVersionKey)
/collection/version/v/[newerSchemaID] => [jsonRepresentation] 
// new key tracking history
/collection/version/p/[newerSchemaID] => [priorSchemaVersionID]
```
by including the newerSchemaID in the key and excluding the priorSchemaVersionID we can ensure that duplicates are not created. `p` and `v` are before the schema ids to allow for more efficient scans of one or the other.  It may be desirable to include `[schemaID]` in the history key to allow for more efficient queries of the history when migrating a record across multiple versions i.e.: `/collection/version/p/[schemaID]/[newerSchemaID] => [priorSchemaVersionID]`.

**Comment by AndrewSisley** [comment]
Is a actually a prerequisite of https://github.com/sourcenetwork/defradb/issues/1448 as the source=>target migration versions map not have a direct/explicit migration (the migration path make be composed of multiple Lenses, e.g. sv1=>sv2=>sv3).

**Comment by jsimnz** [comment]
Moved to #1564
