### ISSUE TITLE
bug: Updating one-to-one relation link makes it act like a one-to-many

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#1646]
Consider one-to-one relation between `Book` and `Author`, Schema:

```gql

type Author {
	name: String
	published: Book @primary
}

type Book {
	name: String
	author: Author
}

```

Consider the following collections to have these documents respectively:

```
Author {
	{name: "author1"} // _docID = "a1"
	{name: "author2"} // _docID = "a2"
}

Book {
	{name: "book1", author: "a1"} // _docID = "b1"
}
```

Doing an `update_Author` query to update it's published book to be `book1` now like so:
`update_Author( id: "a2", data: {published_id: "b1"} )`

### Sets book of both authors as "b1".

Note: similar situation happens even if we do a `update_Book` instead:
 `update_Book(id: "b1", data: {author_id: "a2"})`
 
 
 Some actual tests that document this in our source code:
 - `TestMutationUpdateOneToOne_RelationIDToLinkFromPrimarySide`
 - `TestMutationUpdateOneToOne_RelationIDToLinkFromSecondarySide`
 - `TestBackupImport_WithMultipleNoKeyAndMultipleCollectionsAndMultipleUpdatedDocs_NoError`

**Comment by AndrewSisley** [comment]
Will sort out after: https://github.com/sourcenetwork/defradb/issues/1786
