### ISSUE TITLE
Secondary relation id is unavailable when querying one-one relations

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1654]
See documenting tests:
- `TestQueryOneToOneWithGroupRelatedIDFromSecondary`
- `TestQueryOneToOneWithGroupRelatedIDAliasFromSecondary`

Likely affects all stuff (order, filter) not just group by.
- https://github.com/sourcenetwork/defradb/issues/1670
- https://github.com/sourcenetwork/defradb/issues/1671

**Comment by AndrewSisley** [comment]
> If so, I recall a conversation saying that it shouldn't be possible.

If it shouldn't be possible, the query should error (gql type error).

The problem is likely much bigger than just odd `group by`s though, likely affects filter and order, for which I can think of no good reason for us to not want it to work.  It is likely that a sensible fix would sort out all 3, and any future stuff.

**Comment by fredcarle** [comment]
> If it shouldn't be possible, the query should error (gql type error).

What is the outcome at the moment? 

We should probably test if it's the case for filter and order. From this test it seems that order works no?

**Comment by AndrewSisley** [comment]
> We should probably test if it's the case for filter and order

Of course.

>  From this test it seems that order works no?

I do not understand you here.  There is no order element in the example test.

**Comment by AndrewSisley** [comment]
> We should probably test if it's the case for filter and order

These appear untested atm.

**Comment by fredcarle** [comment]
Just thinking about this. Maybe we should be able to do something like this?
```graphql
Book(groupBy: [author._key]) {
  author {
    _key
  } 
  _group {
    name
    author {
      _key
    } 
  }
}
```
