### ISSUE TITLE
Self referencing relations can be defined with only half the relation

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1698]
E.g.:
```
type User {
	name: String
	age: Int
	boss: User @primary
}
```
There is no way to navigate from boss to minion, and no way to know as to whether this is a one-one or one-many relation.

Attempting to define such a schema should result in an error.

The schema should instead be defined as:

```
type User {
   name: String
   age: Int
   boss: User @primary @relation(name: "boss_minion")
   minion: User @relation(name: "boss_minion")
}
```
Or:
```
type User {
   name: String
   age: Int
   boss: User @primary @relation(name: "boss_minions")
   minions: [User] @relation(name: "boss_minions")
}
```

Likely introduced here: https://github.com/sourcenetwork/defradb/pull/1630/files#diff-d9235077ae433f29bfeef6d78c58be1a43d53804f79ddbe2332cec2fab40b12b

~~Note: This schema is used by some of the backup integration tests and will need to be changed along with the production code.~~ test schema has been fixed

**Comment by fredcarle** [comment]
fixed by #1701
