### ISSUE TITLE
TestQueryOneToOneRelations flaky in CI

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#1702]
`TestQueryOneToOneRelations` often fails on the change detector on the CI. It's not clear yet what is causing this.

It looks to be #1672 - only now flaky instead of consistently failing (and on a different, but similar test).

Possibly significant is that both this and #1672 involved tests with one-one relations.

- Executing `TestQueryOneToOneRelations` only does not resolve the issue (other tests do not appear to be a factor)
- Removing the create statements for either `Publishers` or `Authors` appears to remove the issue
- Reducing the query to just `Book {name}` appears to resolve the issue - this is unlike #1672 which persisted on a simplified query
     - Reducing the query to `Book {name author {name}}` (removing the publisher join) also resolves the issue
     - Reducing the query to `Book {name publisher {name}}` (removing the author join) *does not* resolve the issue. This interestingly is the one-one join (same as #1672)
- Setting `n.subtype.Spans()` does not resolve the issue (is a difference between the primary and secondary)
- No errors in `valuesSecondary` appear to be generated, despite #1711
- Returning early from `valuesSecondary` immediately after `n.subType.Init()` resolves the issue, this is before `n.subType.Next()`
- Returning early from `valuesSecondary` immediately after `n.subType.Next()` does not resolve the issue, suggesting `Next` is the trigger (same as in #1672)
- Removing `n.subType.Init()` from `typeJoinOne.Init()` does not resolve the issue (although it is a duplicate, pointless call I think)
- Updating to badger v4 still has no affect
- ~~Removing the 'extra' `df.kvResultsIter.Close()` call added to the fetcher in #1672  appears to resolve the issue~~ It did for a while, and then broke following a git push

**Comment by AndrewSisley** [comment]
It looks to be https://github.com/sourcenetwork/defradb/issues/1672 - only now flacky instead of consistently failing (and on a different, but similar test)

**Comment by AndrewSisley** [comment]
Oddly, whilst this has been problematic in the CI today, I have no trouble running the change detector on my laptop atm (3 out of 3) (unlike #1672 which was failing pretty consistently locally)

**Comment by fredcarle** [comment]
It fails every third run for me locally. Like clockwork

**Comment by AndrewSisley** [comment]
> It fails every third run for me locally. Like clockwork

I wonder if that is significant.

**Comment by fredcarle** [comment]
> > It fails every third run for me locally. Like clockwork
> 
> I wonder if that is significant. How many times have you seen this set-of-three pattern?

Pretty consistently. So at least 20 times thus far. Sometimes I get 3 or 4 successful runs but it's usually 2 good ones and the third fails. A couple subsequent failures too.
