### ISSUE TITLE
Document updates produce incorrect DAG state.

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#1811]
**Describe the problem**
DAG nodes from *update* mutations contain more than just the fields changed, they contain all the fields defined along with the field(s) changed.

**To Reproduce**
Create a document, update a document, run a commit request for the composite type. Will show a commit with all fields included in the update, when it 

**Expected behavior**
should only include the newest field(s) (delta)

**Additional context**
Potentially related to the LensFetcher, havent confirmed, works in 0.5.1, broken in 0.6.0

**Comment by AndrewSisley** [comment]
This might only affect updates via the planner/gql, as collection.Save (via a UpdateDoc test action) appears to be covered by the semi-broken looking `TestQueryCommitsWithDockeyAndUpdateAndLinks`.  We should definitely have more tests than just this one, for both requests and collection sourced updates.

**Comment by AndrewSisley** [comment]
Will likely fix the bug as part of https://github.com/sourcenetwork/defradb/issues/1816

**Comment by AndrewSisley** [comment]
Lens fetcher does not appear to be responsible.  Leading candidate is the fetcher interface simplication.
