### ISSUE TITLE
Depricate: go-libp2p is removing database-backed peerstore (pstoreds)

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#1902]
Note:
```
// Deprecated: The database-backed peerstore will be removed from go-libp2p in the future.
// Use the memory peerstore (pstoremem) instead.
// For more details see https://github.com/libp2p/go-libp2p/issues/2329
// and https://github.com/libp2p/go-libp2p/issues/2355.
```

In net/node.go we use `"github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoreds"` that creates our peerstore from the underlying defra rootstore with the appropriate prefix. However now if we are forced to use pstoremem

**Comment by nasdf** [comment]
Related #1680

**Comment by shahzadlone** [comment]
https://github.com/sourcenetwork/defradb/pull/1889 will suppress this linter warning but leaving a todo in source-code as the dependencies are piling up.
