### ISSUE TITLE
Flaky test - TestP2PWithMultipleDocumentsWithMultipleUpdatesBeforeConnectSingleDeleteWithShowDeleted

### ISSUE THREAD

**Issue by nasdf** [sourcenetwork/defradb#1929]
Encountered when running http, badger-memory, collection-named matrix 

Failed Job:
https://github.com/sourcenetwork/defradb/actions/runs/6409920767/job/17402130420

**Comment by shahzadlone** [comment]
@nasdf Would be beneficial to link the failed CI runs within the ticket.
