### ISSUE TITLE
Detangle collection storage

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1964]
The way we store collections makes no sense at the moment, and needs to be sorted out.

It should probably be done after https://github.com/sourcenetwork/defradb/issues/1963 though.

There will be the following keys:
```
[Collection.ID] => json // Json should be stored against an immutable index, i.e. not against `Name`
[Collection.Name] => [Collection.ID]  // This means collection names must be unique
```
We also need the following for the short-term, before Collection.GlobalID gets added, as otherwise if a collection is updated to a new schema version, we lose track of what collection it *could* (could as, this only narrows it down) be.
```
[Collection.SchemaVersionId]/[Collection.ID] => nil
```

**Comment by jsimnz** [comment]
Can you add context here on what "no sense". The other issue regarding fetching has great additional info, let's spruce this one up too ;)

**Comment by AndrewSisley** [comment]
> Can you add context here on what "no sense". The other issue regarding fetching has great additional info, let's spruce this one up too ;)

I don't plan on letting this issue live for very long, and it is both tricky and inexact to explain, and in some sense already solved in the WIP branch 1963-collection-feat-detangle

The keys and their values used to persist and index the collection description make no sense.  They are tangled, and with poor names and prefixes. They blend schema with collection very heavily.

**Comment by jsimnz** [comment]
sounds good!

**Comment by fredcarle** [comment]
Currently we have
```go
COLLECTION                        = "/collection/names" // {collectionName} -> schemaVersionID
COLLECTION_SCHEMA                 = "/collection/schema" // {rootSchema} -> schemaVersionID
COLLECTION_SCHEMA_VERSION         = "/collection/version/v" // {schemaVersionID} -> client.CollectionDescription
COLLECTION_SCHEMA_VERSION_HISTORY = "/collection/version/h" // {rootSchemaID}/{previousSchemaVersionID} -> schemaVersionID

SCHEMA_VERSION                    = "/schema/version" // {schemaVersionID} -> client.SchemaDescription 
```

This is what I think we should have:

```go
COLLECTION_NAME                   = "/collection/name" // {collectionName} -> client.CollectionDescription
COLLECTION_ID                     = "/collection/id" // {collectionID} -> collectionName

SCHEMA_VERSION                    = "/schema/version" // {schemaVersionID} -> client.SchemaDescription 
SCHEMA_VERSION_HISTORY            = "/schema/version/h" // {rootSchemaID}/{previousSchemaVersionID} -> schemaVersionID
// maybe also
SCHEMA_ROOT_COLLECTION            = "/schema/root/collection" // "{rootSchemaID}/{collectionName} -> someEmptyMarker
SCHEMA_VERSION_COLLECTION         = "/schema/version/collection" // "{schemaVersionID}/{collectionName} -> someEmptyMarker

```

User will interact most often with collections via their names so it makes sense to have `COLLECTION_NAME` point directly to the collection description.

The P2P system will interact with collections using their collection ID. In this case we have `COLLECTION_ID` pointing to the local collection name which we can use to get the collection description.

The schema description can be stored via `SCHEMA_VERSION` and as we have now, we can store the history via `SCHEMA_VERSION_HISTORY`

There are 2 other avenues that we may want to cover:
1- Getting all collections that were created with a given root schema.
2- Getting all collections that are at a given schema version.
