### ISSUE TITLE
Split build on go releaser

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#2227]
With the change to wasmtime, we need to split the build in the CI to use a matrix of OS so that we can compile using CGO on each of the respective supported OS.

**Comment by shahzadlone** [comment]
When you say ` in the CI` which specific workflow are you referring to? @fredcarle

**Comment by fredcarle** [comment]
> When you say ` in the CI` which specific workflow are you referring to? @fredcarle

The release workflow. Because we switched to wasmtime we need to use CGO to compile so we can't do it on just one runner. We need to split the process on 3 different runners (linux, mac, windows). I'm trying to get that to work at the moment.

**Comment by shahzadlone** [comment]
Ah, makes sense now! Thanks
