### ISSUE TITLE
Unable to remove social accounts mistakenly added

### ISSUE THREAD

**Issue by Dampress** [sourcenetwork/defradb#2329]
I find it difficult to remove the telegram account i mistakenly added. pls work on giving your users the choice to remove accounts they mistakenly added. 
Also, it should not be mandatory for a user to reach a particular level before they can proceed to another task. pls work on that too. 

pls work on the user experience of your site. it looks oversized. 

set the width of your site to 100%

**Comment by fredcarle** [comment]
Hi @Dampress. Thank you for your interest in Open Quest. However, this is the wrong medium to discuss issues related to Open Quest. Please use our Discord server for this.
