### ISSUE TITLE
Collections returned from `db.getCollections` don't have a loaded transaction

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#2384]
`db.getCollections` take a transaction as a parameter but the returned collections aren't loaded with that transaction. This means that subsequent operations using the returned collection will operate on an implicit transaction.

**Comment by AndrewSisley** [comment]
This affects a bunch of stuff, not just `getCollections` - check the refs to `newCollection`.  I suggest adding `txn` as a param to `newCollection`.
