### ISSUE TITLE
`TestQueryWithIndexOnOneToTwoRelation_IfFilterOnIndexedRelation_ShouldFilter` is incorrect

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#2574]
It looks at first glance to be a good test, but it actually shows a one-many being yielded as a one-one (`devices` in the second request is a one-many and should be of type `[]map[string]any`).

Removing the index from the Device.model field results in the correct result.

Possibly related to https://github.com/sourcenetwork/defradb/issues/2577

**Comment by islamaliev** [comment]
@AndrewSisley did you by any chance create a task to enable handling one-many by inverted join?

**Comment by AndrewSisley** [comment]
> @AndrewSisley did you by any chance create a task to enable handling one-many by inverted join?

Yes, the ticket is here: https://github.com/sourcenetwork/defradb/issues/2578
