### ISSUE TITLE
Expand documentation on `CreatePredefinedDocs` test action

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#2600]
There is a lot of magic that goes on in this action, and it is not documented on the action struct.

There is a very good readme here: https://github.com/sourcenetwork/defradb/blob/develop/tests/predefined/README.md

I think a two line summary on the `CreatePredefinedDocs` with a link to the readme would be very handy.

**Comment by islamaliev** [comment]
resolved within #2594
