### ISSUE TITLE
Make cli document generation to directly be put in the website path

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#2645]
Make cli document generation to directly be put in the website path

**Comment by nasdf** [comment]
Closed by https://github.com/sourcenetwork/defradb/pull/2646.

**Comment by shahzadlone** [comment]
> Closed by #2646.

Oh wow, it didn't automatically close this one?

**Comment by shahzadlone** [comment]
OH lol I had a type in the PR description that's why `Resovles` instead of `Resolves`:

```
Resolves #2166
Resovles #2645
```
Cheers
