### ISSUE TITLE
`defradb identity new` returns keys in encoding not supported by defra calls

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#2770]
The private key returned from `defradb identity new` is binary encoded, whereas the defra only accepts hex-encoded identity private keys.

The encoding of the value returned from `defradb identity new` is also not documented.

**Comment by shahzadlone** [comment]
Defra cli accepts hex encoded private key (which I believe is a stop gap solution until proper way to pass the key is introduced, i.e. using keyring). @nasdf can confirm perhaps.

The util command can be used to generate a pair and then the user is responsible how to and where to store it, they can store it in their key ring for example

As for the documentation of the encoding of the values, I can document it.
