### ISSUE TITLE
Change detector keeps failing due to doc encrypt test `TestDocEncryption_UponEncryptionSeveralDocs_ShouldStoreAllCommitsDeltaEncrypted`

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#2812]
Started noticing change detector fails after rebasing the latest commit on develop: https://github.com/sourcenetwork/defradb/commit/24fa14f895644621915e4bf65d41469c7dc52979

Failing test: `TestDocEncryption_UponEncryptionSeveralDocs_ShouldStoreAllCommitsDeltaEncrypted`

Failed runs:
- https://github.com/sourcenetwork/defradb/actions/runs/9813511994/job/27099625664?pr=2811
- https://github.com/sourcenetwork/defradb/actions/runs/9797928722/job/27055488520

**Comment by islamaliev** [comment]
how ofter does it happen?

Maybe we can try to remove all `NewDocIndex` calls from the related tests and replaces them with real doc ids.

**Comment by AndrewSisley** [comment]
> Maybe we can try to remove all `NewDocIndex` calls from the related tests and replaces them with real doc ids.

Doc IDs should very much be consistent across processes, if they are not something is very broken and we should fix that instead of removing `NewDocIndex` calls

**Comment by AndrewSisley** [comment]
This is probably caused by the encrypted state not being deterministic: https://security.stackexchange.com/questions/42642/should-aes-always-give-the-same-output
