### ISSUE TITLE
Getting Started doc broken on create a document

### ISSUE THREAD

**Issue by crystal-koii** [sourcenetwork/defradb#2977]
**Describe the problem**
_key doesn't exist on schema so it throws error:
```
defradb client query '
  mutation {
      create_User(input: {age: 31, verified: true, points: 90, name: "Bob"}) {
          _key             
      }
  }
> '
------ Request Results ------
{
  "data": null,
  "errors": [
    "Cannot query field \"_key\" on type \"User\"."
  ]
}

```

**To Reproduce**
Follow getting started https://docs.source.network/defradb

**Expected behavior**
```
{
  "data": [
    {
      "_key": "bae-91171025-ed21-50e3-b0dc-e31bccdfa1ab",
    }
  ]
}
```
**Solution***
Update docs to return something that actually exists:
```
defradb client query '
mutation {
    create_User(input: {age: 31, verified: true, points: 90, name: "Bob"}) {
        _docID
    }
}
'
------ Request Results ------
{
  "data": {
    "create_User": [
      {
        "_docID": "bae-36fb9a9a-7af6-50cc-bc43-82e4c742a53e"
      }
    ]
  },
  "errors": null
}
```
NOTE: Also need to update everywhere else _key is used, it seems like _key has been replaced with _docID

**Comment by fredcarle** [comment]
Thanks for opening the issue @crystal-koii. We do indeed need to update the docs to reflect the change from `_key` to `_docID`. The docs content is located within this repo. Was it your intention to make the changes yourself and open a PR for it?
