### ISSUE TITLE
Remove Name from block links 

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#3056]
It is not required and just consumes CPU/network/storage resources and complicates the introduction of new stuff like https://github.com/sourcenetwork/defradb/issues/3038

**Comment by jsimnz** [comment]
Can you expand on this? Are you referring to the name inside a block that is linked.

Or the name of a link within a block? 

If it's the latter, I don't see how we can remove it, since we need to (quickly) differentiate between types of links (eg "head" vs field link).

Named links are also necessary for ipld selectors

**Comment by AndrewSisley** [comment]
Discussed on standup and rejected.  Name field deemed to be valuable in the future.

WIP branch name is `3056-rm-block-link-names` (my in my fork).

I tested the space savings for non-branchable collections. With a database size of 10 documents with 3 fields (age, name, email), and a single update to each age field, the change reduced the size of the blockstore by 3.79%, and the total size of the database by 2.57%.   The percentage savings will increase with field name length, but decrease with field value size.

The impact on branchable collections will be much higher as a much higher percentage of the block is links/link-names.

**Comment by AndrewSisley** [comment]
We want this to allow us to use GraphSync https://github.com/ipfs/go-graphsync in the future, it *might* be used for some ACP related client-side optimisation (debated), it *will* be exposed to users to allow them to sync only x,y,z fields to a node.

**Comment by AndrewSisley** [comment]
>  We want this to allow us to use GraphSync https://github.com/ipfs/go-graphsync in the future, it might be used for some ACP related client-side optimisation (debated), it will be exposed to users to allow them to sync only x,y,z fields to a node.

Documented in codebase
