### ISSUE TITLE
Use govulncheck in CI

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#522]
Go introduces new tooling for vulnerability detection: [golang.org/x/vuln/vulncheck](https://pkg.go.dev/golang.org/x/vuln/vulncheck)

> Command govulncheck reports known vulnerabilities that affect Go code. It uses static analysis or a binary's symbol table to narrow down reports to only those that potentially affect the application. For more information about the API behind govulncheck, see [https://go.dev/security/vulncheck](https://go.dev/security/vulncheck).

Because it is experimental it could potentially report false positives, thereby "blocking" PRs. We can be mindful of that and perhaps additionally it shouldn't be enabled on the develop/main branch checks, just on PRs.

**Comment by shahzadlone** [comment]
Use govulncheck to find vulnerabilities and update go version in the future.

I gave it a dry run and all our vulnerabilities that it was showing on go1.19 version were fixed by just bumping to go1.20
