### ISSUE TITLE
Update code documentation to Go 1.19 documentation syntax

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#563]
Part of #153 

Update code documentation to new format provided by Go 1.19, with headings, lists, URL links, documentation/symbol links, and overall new syntax.

https://github.com/golang/proposal/blob/master/design/51082-godocfmt.md

**Comment by AndrewSisley** [comment]
Closing, as it seems unlikely that anyone we dedicate a large chunk of time for this anytime soon and keeping it is not worth the backlog noise.  It also growing out of date
