### ISSUE TITLE
Zapper errors can leak out to the user

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#565]
Issue created from discussion here: https://github.com/sourcenetwork/defradb/pull/552#discussion_r907699449

Whilst we now actively validate log file paths, there is a race condition here where by the file paths may no longer be valid at the time of logging, resulting in zap log errors being exposed to the consumer.  Look at preventing this somehow.

**Comment by fredcarle** [comment]
Stale
