### ISSUE TITLE
Resolve the rough edges around the mapper/mapping package DX flow.

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#606]
As mentioned a [few times](https://github.com/sourcenetwork/defradb/pull/471#pullrequestreview-1019739212) in #471 the DevEx flow of using the `mapper` package within the `query` planner and elsewhere, as well as its relation to the `parser` package, needs to be refined.

This is a tracking issue for that effort. It doesn't need to be done all at once, but we can 
1) Identify the concrete instances
2) Address "low-hanging" instances
3) Continue to make more core refactor changes as necessary.

Child issues:
- [x] https://github.com/sourcenetwork/defradb/issues/566

**Comment by fredcarle** [comment]
Stale
