### ISSUE TITLE
Support Well-Known URIs

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#703]
https://www.rfc-editor.org/rfc/rfc8615#section-3

The basic use is to allow an application to indicate it offers the "defradb" service.

Up for consideration to be implemented or not, and if so, when. (probably only after v0.6). If we do implement, then we can add to official registry via https://github.com/protocol-registries/well-known-uris

**Comment by fredcarle** [comment]
Stale
