### ISSUE TITLE
DocKey UUIDv5/SHA1 refactor

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#862]
Currently our DocKeys are UUIDv5, which effectively takes some arbitrary input, and applies a SHA1 hash and inserting that into the UUID data field.

This was implemented originally because UUIDv5 was the only spec compliant way to fit our CIDs into a UUID format. But there are many issues in using SHA1, as it is effectively considered a broken hash (susceptible to chosen text attacks).

Ideally we would use a stronger hash function, or the CID/Multihash data directly but the UUID spec didn't have a compliant way to achieve this.

But, theres a new draft spec for the next iteration of UUIDs (v6, v7, and v8). The one of interest is the UUIDv8, as its a blank/custom UUID version that soley maintains format and backwards compatability.

This allows us to fill the 122 bits with anything we want.

Theres a few options we can use. Our requirements are that they are A) Cryptographically secure B) Can fit within 122 (either direct hash output, or with truncation).

Suggestions:
- SHA256, truncated from 256 bits to 120 bits would give 60-bits of security, which is probably a little too low. However, we do fix [length-extension attacks](https://cryptologie.net/article/417/how-did-length-extension-attacks-made-it-into-sha-2/) that exist on SHA256 by truncating. 
- more to come

**Comment by fredcarle** [comment]
From discussion between John and Bruno, decision has been made that this is not high priority at this point and the issue can be closed.
