### ISSUE TITLE
Use order independant CID generation for SchemaID

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#863]
At the moment, I *think* its based on a JSON input to the multihash function, which is *order dependant*. We need to change so that it matches the dockey version CID generation, so that it is order *independant*. IE: Use CBOR.

```[tasklist]
### Prerequisites
- [ ] https://github.com/sourcenetwork/defradb/issues/851
- [ ] #852
```

**Comment by AndrewSisley** [comment]
Blocked behind the other cid changing issues
