### ISSUE TITLE
[Epic] Decouple defra from gql

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#864]
Would like to reorganize the relationship between defra and gql. At the moment defra is a GQL database, however it would be fairly easy to decouple the two - I think this would make for a cleaner separation of concerns (preventing conceptual leaks), and gives us the opportunity to support more query languages in the future.  It also removes the string/gql dependency from the collection ABI, and IMO makes it easier for source-dev/author specialization as the query language separated from the core db engine. It also provides cleaner guarantees that gql-elements are not persisted in defra (boosting interop) (e.g. saved in the schema). 

The gql aspect (including generator) becomes a layer on top of defra (including constants).  It is removed from the collection abi).  The collection abi takes a well defined `mapper.Select` like type as a parameter, optimized for users, this gets converted to the `mapper.Select` (optimized for internal usage) within the planner package, the gql package parses the gql into the `client/collection.Select`.

- https://github.com/sourcenetwork/defradb/issues/566

**Comment by nasdf** [comment]
Related #1845

**Comment by AndrewSisley** [comment]
This has pretty much been completed, we may encounter some small leftovers when we get round to adding other query langs
