### ISSUE TITLE
Document serialization needs strong typing

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#935]
Broken out from https://github.com/sourcenetwork/defradb/pull/931/files#r1017152428

At the moment, there isn't enforced type validation/safety when creating documents, only on updating docs.

This causes various issues, but it came to light while working on #931 because DateTime fields are getting serialized as strings, and there's no entry point to conviently handle this atm.

**Comment by AndrewSisley** [comment]
Suggest doing this after https://github.com/sourcenetwork/defradb/issues/1830

**Comment by AndrewSisley** [comment]
Also blocked by https://github.com/sourcenetwork/defradb/issues/1847
