### ISSUE TITLE
General results returned from the db must have deterministic order

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#958]
results returned from the db should have deterministic order

**Comment by jsimnz** [comment]
To be fair, "must" and "should" often intentionally mean different things in spec documents.

Also @shahzadlone is this specifically referring to the order of the fields, or the order of the general results. As it is written, the issue is ambiguous.

**Comment by shahzadlone** [comment]
This is regarding returned result after a request is issued, not about the field order.

**Comment by jsimnz** [comment]
What do you mean by deterministic? Can you give some examples?

**Comment by AndrewSisley** [comment]
Closing, as ticket lacks sufficient information to work on and has been stale for a long time
